### ISSUE TITLE
Version 3.0.0 breaks ident, 3.0.0-pre.6 still working

### ISSUE THREAD

**Issue by ihatemicrosoft-was-already-taken** [thelounge/thelounge-docker#76]
Thelounge is working for me in 3.0.0-pre.6-alpine

I just updated to 3.0.0-alpine, but starting throws this error:

```thelounge    | 2019-01-28T07:31:55.457953223Z 2019-01-28 07:31:55 [INFO] The Lounge v3.0.0 (Node.js 10.15.0 on linux x64)
thelounge    | 2019-01-28T07:31:55.458672438Z 2019-01-28 07:31:55 [INFO] Configuration file: /var/opt/thelounge/config.js
thelounge    | 2019-01-28T07:31:55.494777857Z 2019-01-28 07:31:55 [INFO] Available at http://0.0.0.0:9000/ in private mode
thelounge    | 2019-01-28T07:31:55.549306537Z events.js:167
thelounge    | 2019-01-28T07:31:55.549386137Z       throw er; // Unhandled 'error' event
thelounge    | 2019-01-28T07:31:55.549425519Z       ^
thelounge    | 2019-01-28T07:31:55.549455714Z
thelounge    | 2019-01-28T07:31:55.549481034Z Error: listen EACCES: permission denied 0.0.0.0:113
thelounge    | 2019-01-28T07:31:55.549511348Z     at Server.setupListenHandle [as _listen2] (net.js:1273:19)
thelounge    | 2019-01-28T07:31:55.549545488Z     at listenInCluster (net.js:1338:12)
thelounge    | 2019-01-28T07:31:55.549580186Z     at Server.listen (net.js:1425:7)
thelounge    | 2019-01-28T07:31:55.549615601Z     at new Identification (/usr/local/share/.config/yarn/global/node_modules/thelounge/src/identification.js:27:11)
thelounge    | 2019-01-28T07:31:55.549643474Z     at Server.server.listen (/usr/local/share/.config/yarn/global/node_modules/thelounge/src/server.js:172:3)
thelounge    | 2019-01-28T07:31:55.549668805Z     at Object.onceWrapper (events.js:273:13)
thelounge    | 2019-01-28T07:31:55.549703533Z     at Server.emit (events.js:182:13)
thelounge    | 2019-01-28T07:31:55.549736259Z     at emitListeningNT (net.js:1324:10)
thelounge    | 2019-01-28T07:31:55.549764350Z     at process._tickCallback (internal/process/next_tick.js:63:19)
thelounge    | 2019-01-28T07:31:55.549798610Z     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
thelounge    | 2019-01-28T07:31:55.549831883Z Emitted 'error' event at:
thelounge    | 2019-01-28T07:31:55.549864984Z     at emitErrorNT (net.js:1317:8)
thelounge    | 2019-01-28T07:31:55.549898415Z     at process._tickCallback (internal/process/next_tick.js:63:19)
thelounge    | 2019-01-28T07:31:55.550760353Z     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
thelounge    | 2019-01-28T07:31:55.550796300Z     at startup (internal/bootstrap/node.js:283:19)
thelounge    | 2019-01-28T07:31:55.550828238Z     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)```

Back to 3.0.0-pre.6-alpine everything is just fine.

**Comment by xPaw** [comment]
Try running ident at a higher port and when running docker, map it back to 113 (if you run it this way)

**Comment by ihatemicrosoft-was-already-taken** [comment]
That did seem to do the trick. Thanks!

**Comment by xPaw** [comment]
We should mention this in the readme, do you want to make a pr?

The reason it broke now is we dropped root permissions in the final release.
